set -g status-style "bg=default,fg=#839496"
set -g window-status-current-style "bg=#268bd2,fg=#002b36,bold"
set -g window-status-style "fg=#586e75"
set -g pane-border-style "fg=#586e75"
set -g pane-active-border-style "fg=#268bd2"
set -g message-style "bg=#268bd2,fg=#002b36"
set -g mode-style "bg=#073642,fg=#839496"
