set -g status-style "bg=default,fg=#3c3836"
set -g window-status-current-style "bg=#076678,fg=#fbf1c7,bold"
set -g window-status-style "fg=#928374"
set -g pane-border-style "fg=#928374"
set -g pane-active-border-style "fg=#076678"
set -g message-style "bg=#076678,fg=#fbf1c7"
set -g mode-style "bg=#ebdbb2,fg=#3c3836"
