set -g status-style "bg=default,fg=#575279"
set -g window-status-current-style "bg=#907aa9,fg=#faf4ed,bold"
set -g window-status-style "fg=#9893a5"
set -g pane-border-style "fg=#9893a5"
set -g pane-active-border-style "fg=#907aa9"
set -g message-style "bg=#907aa9,fg=#faf4ed"
set -g mode-style "bg=#f2e9e1,fg=#575279"
