set -g status-style "bg=default,fg=#e0def4"
set -g window-status-current-style "bg=#c4a7e7,fg=#191724,bold"
set -g window-status-style "fg=#6e6a86"
set -g pane-border-style "fg=#6e6a86"
set -g pane-active-border-style "fg=#c4a7e7"
set -g message-style "bg=#c4a7e7,fg=#191724"
set -g mode-style "bg=#26233a,fg=#e0def4"
