[theme]
name = "themer"

[colors]
AlertInfo = "#8ea4a2"
AlertWarn = "#b6927b"
AlertError = "#c4746e"
Annotation = "#8ba4b0"
Base = "#c5c9c5"
Guidance = "#a6a69c"
Important = "#c4746e"
Title = "#8ba4b0"
