[theme.custom]
panel_bg = "#181616"
surface0 = "#1a1818"
surface1 = "#282727"
surface_dim = "#0d0c0c"
overlay0 = "#393836"
overlay1 = "#a6a69c"
text = "#c5c9c5"
subtext0 = "#a6a69c"
accent = "#8ba4b0"
mauve = "#a292a3"
green = "#8a9a7b"
yellow = "#c4b28a"
red = "#c4746e"
blue = "#8ba4b0"
teal = "#8ea4a2"
peach = "#b6927b"
