set -g status-style "bg=default,fg=#657b83"
set -g window-status-current-style "bg=#268bd2,fg=#fdf6e3,bold"
set -g window-status-style "fg=#93a1a1"
set -g pane-border-style "fg=#93a1a1"
set -g pane-active-border-style "fg=#268bd2"
set -g message-style "bg=#268bd2,fg=#fdf6e3"
set -g mode-style "bg=#eee8d5,fg=#657b83"
